application: glass-setting-831
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: webapp/app/index.html
  upload: webapp/app/(.*\.html)
  
- url: /partials
  static_dir: webapp/app/partials
  
- url: /data
  static_dir: webapp/app/data
  
- url: /css
  static_dir: webapp/app/css
 
- url: /js
  static_dir: webapp/app/js
 
- url: /bower_components
  static_dir: webapp/app/bower_components
 
 
- url: /.*
  script: go app