application: glass-setting-831
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: Webdir/app/index.html
  upload: Webdir/app/(.*\.html)
  
- url: /partials
  static_dir: Webdir/app/partials
  
- url: /data
  static_dir: Webdir/app/data
  
- url: /css
  static_dir: Webdir/app/css
 
- url: /images
  static_dir: Webdir/app/images
 
- url: /js
  static_dir: Webdir/app/js
 
- url: /bower_components
  static_dir: Webdir/app/bower_components
 
 
- url: /.*
  script: go app